export interface HealthEntry {
  date: string;
  energy: number;
  sleep: number;
  symptoms: string[];
  respiratory: number;
  temperature: number;
  mood: number;
  appetite: number;
  lifestyle: string;
}

export const mockHealthData: HealthEntry[] = [
  {
    date: '2025-02-21',
    energy: 7,
    sleep: 8,
    symptoms: [],
    respiratory: 90,
    temperature: 98.2,
    mood: 8,
    appetite: 7,
    lifestyle: 'active',
  },
  {
    date: '2025-02-20',
    energy: 6,
    sleep: 7,
    symptoms: ['mild headache'],
    respiratory: 85,
    temperature: 98.1,
    mood: 7,
    appetite: 6,
    lifestyle: 'moderate',
  },
  {
    date: '2025-02-19',
    energy: 8,
    sleep: 8,
    symptoms: [],
    respiratory: 92,
    temperature: 98.0,
    mood: 9,
    appetite: 8,
    lifestyle: 'active',
  },
  {
    date: '2025-02-18',
    energy: 5,
    sleep: 6,
    symptoms: ['fatigue', 'dry cough'],
    respiratory: 75,
    temperature: 98.5,
    mood: 6,
    appetite: 5,
    lifestyle: 'rest',
  },
  {
    date: '2025-02-17',
    energy: 7,
    sleep: 8,
    symptoms: ['dry cough'],
    respiratory: 80,
    temperature: 98.3,
    mood: 7,
    appetite: 7,
    lifestyle: 'moderate',
  },
  {
    date: '2025-02-16',
    energy: 8,
    sleep: 8,
    symptoms: [],
    respiratory: 93,
    temperature: 98.0,
    mood: 8,
    appetite: 8,
    lifestyle: 'active',
  },
  {
    date: '2025-02-15',
    energy: 6,
    sleep: 7,
    symptoms: ['throat irritation'],
    respiratory: 82,
    temperature: 98.2,
    mood: 7,
    appetite: 6,
    lifestyle: 'moderate',
  },
  {
    date: '2025-02-14',
    energy: 9,
    sleep: 8,
    symptoms: [],
    respiratory: 95,
    temperature: 98.0,
    mood: 9,
    appetite: 9,
    lifestyle: 'active',
  },
  {
    date: '2025-02-13',
    energy: 7,
    sleep: 7,
    symptoms: [],
    respiratory: 88,
    temperature: 98.1,
    mood: 8,
    appetite: 7,
    lifestyle: 'moderate',
  },
  {
    date: '2025-02-12',
    energy: 6,
    sleep: 6,
    symptoms: ['fatigue'],
    respiratory: 78,
    temperature: 98.4,
    mood: 6,
    appetite: 6,
    lifestyle: 'rest',
  },
  {
    date: '2025-02-11',
    energy: 8,
    sleep: 8,
    symptoms: [],
    respiratory: 91,
    temperature: 98.0,
    mood: 8,
    appetite: 8,
    lifestyle: 'active',
  },
  {
    date: '2025-02-10',
    energy: 7,
    sleep: 8,
    symptoms: [],
    respiratory: 89,
    temperature: 98.1,
    mood: 7,
    appetite: 7,
    lifestyle: 'moderate',
  },
  {
    date: '2025-02-09',
    energy: 8,
    sleep: 8,
    symptoms: [],
    respiratory: 94,
    temperature: 98.0,
    mood: 9,
    appetite: 8,
    lifestyle: 'active',
  },
  {
    date: '2025-02-08',
    energy: 7,
    sleep: 7,
    symptoms: [],
    respiratory: 87,
    temperature: 98.2,
    mood: 8,
    appetite: 7,
    lifestyle: 'moderate',
  },
];

export const userProfile = {
  name: 'Amara',
  age: 28,
  streak: 14,
  healthScore: 72,
  tier: 'Gold',
  discount: '15%',
  joinDate: '2024-11-21',
};

export const clinics = [
  {
    id: 1,
    name: 'Wellness Medical Center',
    specialty: 'Respiratory Health',
    rating: 4.8,
    distance: 2.3,
    discountCode: 'PULSE-AMR-2024',
    discount: '15%',
  },
  {
    id: 2,
    name: 'City Health Clinic',
    specialty: 'General Health',
    rating: 4.6,
    distance: 3.1,
    discountCode: 'PULSE-AMR-2024',
    discount: '15%',
  },
];

export const checkInCategories = [
  { id: 'energy', label: 'Energy', icon: 'zap', scale: 'low-high' },
  { id: 'sleep', label: 'Sleep', icon: 'moon', scale: 'poor-great' },
  { id: 'symptoms', label: 'Symptoms', icon: 'activity', scale: 'none-severe' },
  { id: 'respiratory', label: 'Respiratory', icon: 'wind', scale: 'percent' },
  { id: 'temperature', label: 'Temperature', icon: 'thermometer', scale: 'celsius' },
  { id: 'mood', label: 'Mood', icon: 'smile', scale: 'sad-happy' },
  { id: 'appetite', label: 'Appetite', icon: 'utensils', scale: 'none-great' },
  { id: 'lifestyle', label: 'Lifestyle', icon: 'activity', scale: 'rest-active' },
];
